config/routes.rb
Rails.application.routes.draw do
  resources :books
  get 'welcome/index'

  resources :people

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :content)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController


	def index
		@personas = Person.all
		Holidays.load_custom('jolijoli.yaml')
		date = Date.civil(2013,8,12)
		date_custom = Holidays.on(date, :custom)
		Rails.logger.info date_custom
	end

	def new
		@person = Person.new
	end
	ssasaD
	def create
		person = Person.new
		person.name = params[:person][:name]
		person.dni = params[:person][:dni]
		person.save
		Rails.logger.info params[:person][:name]
		puts params[:person][:dni]
		people = Person.all
		puts people.class
		respond_to do |format|
	      if person.save
	        format.html { redirect_to people_path, notice: 'Book was successfully created.' }
	        format.json { render :show, status: :created, location: people }
	      else
	        format.html { render :new }
	        format.json { render json: people.errors, status: :unprocessable_entity }
	      end
	    end
	end
	Master
	def show
	end

	def edit
		Rails.logger.info params
		puts "CONTEEENT"
		@person = Person.find(params[:id])
	end

	def update
		respond_to do |format|
			Rails.logger.info params
			puts "PARAMS ARRIBA"
			act = Person.find(params[:id])
			actualizador = {"name": params[:person][:name], "dni": params[:person][:dni]}
			act.update(actualizador)
			#act.name = params[:person][:name]
			#act.dni = params[:person][:dni]
			#act.save
	        format.html { redirect_to people_path, notice: 'Book was successfully updated.' }
	        format.json { render :show, status: :ok, location: people }
	    end
	end

	def destroy
	    dest = Person.find(params[:id])
	    dest.destroy
	    respond_to do |format|
			format.html { redirect_to people_path, notice: 'Book was successfully destroyed.' }
			format.json { head :no_content }
	    end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.content %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @book.content %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfirstapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :dni %>
    <%= f.text_field :dni %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<!DOCTYPE html>
<html>
	<head><title>Lista de Personas</title></head>
	<body>
		<table>
			<thead>
				<tr>
					<th>Nombre</th>
					<th>DNI</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
				<% for x in @personas do %>
				<tr>
					<td><%= x.name %></td>
					<td><%= x.dni %></td>
					<td><%= link_to "Editar" , edit_person_path(x) %></td>
					<td><%= link_to 'Eliminar', x, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<%= link_to 'Agregar', new_person_path %>
	</body>
</html>

app/views/people/new.html.erb
<%= form_for @person do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :dni %><br>
    <%= form.text_field :dni %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/people/show.html.erb
<!DOCTYPE html>
<html>
	<head><title>Lista de Personas</title></head>
	<body>
		<table>
			<thead>
				<tr>
					<th>Nombre</th>
					<th>DNI</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
				<% for x in @personas do %>
				<tr>
					<td><%= x.name %></td>
					<td><%= x.dni %></td>
					<td><%= link_to "Editar" , edit_person_path(x) %></td>
					<td><%= link_to "Eliminar" , x , method: :destroy %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<%= link_to 'Agregar', new_person_path %>
	</body>
</html>

app/views/welcome/index.html.erb
<h1>My First App</h1>